version: '3.8'
services:
  django:
    build: backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "./backend:/app"
    environment:
      - DJANGO_SECRET=your_secret_key
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=ticketoo.settings
