# Generated by Django 4.1.4 on 2023-01-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tickets', '0001_initial'), ('tickets', '0002_remove_ticket_reduced_ticketsale'), ('tickets', '0003_alter_ticket_unique_together'), ('tickets', '0004_remove_ticketsale_date'), ('tickets', '0005_alter_ticket_duration'), ('tickets', '0006_rename_reuced_ticketsale_reduced')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'unique_together': {('duration', 'zone', 'price')},
            },
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reduced', models.BooleanField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
