# Generated by Django 4.1.4 on 2022-12-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_reduced_ticketsale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('duration', 'zone', 'price')},
        ),
    ]
